#!/bin/bash

# curl me in by:
# $ curl 'https://raw.githubusercontent.com/vindennl48/dotfiles/master/arch_install' > arch_install
# $ chmod a+x arch_install

echo '- Make sure you run `wifi-menu` and connect to wifi first'
echo '- Make sure you change $DISK value to what disk you want to'
echo '  install onto! '
echo '- Also, make sure this drive is CLEAR first!'
echo '- Lastly, set desired partition sizes within this file!'
echo ''

read -p "Have you completed the above steps? If yes (y), If no (CTRL+C)." choice

DISK='sdx'        # change this to desired drive
BOOT_SIZE='+200M'
ROOT_SIZE=''      # '' will select default size

function pre_install {
timedatectl set-ntp true
fdisk /dev/$DISK <<EOF
o
n
p
1

$BOOT_SIZE
a
n
p
2

$ROOT_SIZE
p
w
EOF

mkfs.ext4 /dev/"$DISK"1
mkfs.ext4 /dev/"$DISK"2

mount /dev/"$DISK"2 /mnt
mkdir /mnt/boot /mnt/home
mount /dev/"$DISK"1 /mnt/boot

pacstrap /mnt linux linux-firmware base base-devel networkmanager vim git

genfstab -U /mnt >> /mnt/etc/fstab

cp arch_install /mnt/.
echo "----> You must edit the copied installer in /mnt to uncomment 'post_install' and comment 'pre_install' at the bottom, then run."
arch-chroot /mnt
}

function post_install {
systemctl enable NetworkManager

mkinitcpio -p linux

pacman -S --needed --noconfirm grub
grub-install --target=i386-pc /dev/"$DISK"
grub-mkconfig -o /boot/grub/grub.cfg


echo    "----> Set password for root"
read -p "      (Press ENTER to continue)" choice
passwd


echo    "----> Set locales, uncomment all en_US"
read -p "      (Press ENTER to continue)" choice
vim /etc/locale.gen
locale-gen

echo "LANG=en_US.UTF-8" > /etc/locale.conf

ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime

echo "arch" > /etc/hostname


echo    "----> Set wheel permissions: uncomment 'wheel ALL=(ALL) ALL' and add 'Defaults !tty_tickets'"
read -p "      (Press ENTER to continue)" choice
vim /etc/sudoers

echo    "----> Make sure to exit to main screen and un-mount /mnt!"
read -p "      (Press ENTER to continue)" choice
}

# Comment out the one you are NOT installing
pre_install
#post_install

