#!/bin/bash

# curl me in by:
# $ curl 'https://raw.githubusercontent.com/vindennl48/dotfiles/master/arch_install' > arch_install
# $ chmod a+x arch_install

echo '- Make sure you run `wifi-menu` and connect to wifi first'
echo '- Make sure you change $DISK value to what disk you want to'
echo '  install onto! '
echo '- Also, make sure this drive is CLEAR first!'
echo '- Lastly, set desired partition sizes within this file!'
echo ''

read -p "Have you completed the above steps? If yes (y), If no (CTRL+C)." choice

DISK='sdx'        # change this to desired drive
BOOT_SIZE='+200M'
SWAP_SIZE='+200M'
ROOT_SIZE=''      # '' will select default size

function pre_install {
timedatectl set-ntp true
fdisk /dev/$DISK <<EOF
n
p
1

$BOOT_SIZE
n
p
2

$SWAP_SIZE
n
p
3

$ROOT_SIZE
w
EOF

cryptsetup -y -v luksFormat --type luks2 /dev/"$DISK"3

cryptsetup open /dev/"$DISK"3 cryptroot

mkfs.ext4 /dev/"$DISK"1
mkfs.ext4 /dev/mapper/cryptroot
mkswap /dev/"$DISK"2
swapon /dev/"$DISK"2

mount /dev/mapper/cryptroot /mnt
mkdir /mnt/boot /mnt/home
mount /dev/"$DISK"1 /mnt/boot

pacstrap /mnt base base-devel vim git

genfstab -U /mnt >> /mnt/etc/fstab

cp arch_install /mnt/.
arch-chroot /mnt
}

function post_install {
read -p "Add hooks to next file: \n base udev autodetect keyboard keymap modconf block encrypt filesystems fsck" choice
vim /etc/mkinitcpio.conf
mkinitcpio -p linux

pacman -S grub
grub-install --target=i386-pc /dev/"$DISK"
read -p "Add cryptdevice to grub: \n GRUB_CMDLINE_LINUX=\"cryptdevice=/dev/sda3:cryptroot\"" choice
vim /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

read -p "Set password for root" choice
passwd

read -p "Set locales, uncomment all en_US" choice
vim /etc/locale.gen
locale-gen

echo "LANG=en_US.UTF-8" > /etc/locale.conf

ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime

echo "arch" > /etc/hostname

read -p "Set wheel permissions: uncomment 'wheel ALL=(ALL) ALL' and add 'Defaults !tty_tickets' " choice
vim /etc/sudoers

read -p "Make sure to exit to main screen and un-mount /mnt!" choice
}

# Comment out the one you are NOT installing
pre_install
#post_install

