#!/bin/bash

function Install {
  # Programs with no additional work
  ##########################################
    if [[ "$isDebian" =~ ^/ ]]; then
      sudo apt update && sudo apt -y upgrade
      sudo apt install -y \
        cmake \
        curl \
        htop \
        silversearcher-ag \
        tree \
        chromium-browser \
	python3 \
	python3-pip \

    elif [[ "$isArch" =~ ^/ ]]; then
      sudo pacman -Syu
      sudo pacman -S \
        cmake \
        curl \
        htop \
        the_silver_searcher \
        tree \
        ttf-freefont \
        chromium \
        python \
        python-pip \

    fi
  ##########################################

  # Programs with additional work needed
  # These include custom dotfiles!
  ######################################
    #install_setbright_arch_only
    install_git
    #install_openssh
    #install_docker
    #install_docker_compose
    #install_heroku_debian_only
    install_fzf
    #install_termite_arch_only
    #install_rvm_arch_only
    #install_xorg_arch_only
    #install_i3_gaps_arch_only # depends on xorg
    #install_atigfx_arch_only
    #install_vbox_arch_only # only if inside VirtualBox!
    install_neovim_tmux

    # MUST BE LAST!
    install_zsh_and_oh_my_zsh
  ######################################
}

# Additional work installs below
################################

isDebian=$(type -P apt-get)
isArch=$(type -P pacman)

function install_setbright_arch_only {
  if [[ "$isArch" =~ ^/ ]]; then
    sudo ln -s $HOME/bin/dotfiles/i3/backlight.rules /etc/udev/rules.d/.
    sudo usermod -aG video $USER
  fi

  # Git custom dotfiles
  ln -s $HOME/bin/dotfiles/git/gitconfig $HOME/.gitconfig
}

function install_git {
  if [[ "$isDebian" =~ ^/ ]]; then
    sudo apt install -y git
  elif [[ "$isArch" =~ ^/ ]]; then
    sudo pacman -S git
  fi

  # Git custom dotfiles
  rm $HOME/.gitconfig
  ln -s $HOME/bin/dotfiles/git/gitconfig $HOME/.gitconfig
}

function install_neovim_tmux {
  if [[ "$isDebian" =~ ^/ ]]; then
    sudo apt install -y neovim tmux
  elif [[ "$isArch" =~ ^/ ]]; then
    sudo pacman -S neovim tmux
    sudo pip install neovim
  fi

  # Neovim custom dotfiles
  mkdir -p ~/.local/share/nvim/site/autoload/
  mkdir -p ~/.config/nvim/
  echo ':source $MYNVIMPATH/init.vim' > $HOME/.config/nvim/init.vim
  git clone https://github.com/junegunn/vim-plug.git $HOME/.local/share/nvim/site/autoload/vim-plug
  cp $HOME/.local/share/nvim/site/autoload/vim-plug/plug.vim $HOME/.local/share/nvim/site/autoload/.
  rm -Rf $HOME/.local/share/nvim/site/autoload/vim-plug

  # Tmux custom dotfiles
  ln -s $MYTMUXPATH/tmux.conf $HOME/.tmux.conf
}

function install_openssh {
  if [[ "$isDebian" =~ ^/ ]]; then
    sudo apt install -y openssh-server
  elif [[ "$isArch" =~ ^/ ]]; then
    sudo pacman -S openssh
  fi
  sudo systemctl restart ssh
}

function install_fzf {
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  $HOME/.fzf/install
}

function install_zsh_and_oh_my_zsh {
  if [[ ! "$(which zsh)" =~ ^/ ]]; then

    if [[ "$isDebian" =~ ^/ ]]; then
      sudo apt -y install zsh
    elif [[ "$isArch" =~ ^/ ]]; then
      sudo pacman -S zsh zsh-completions
    fi
    chsh -s $(which zsh)

    read -p "You must type exit at the next prompt to finish install!" en
 
    # Install oh-my-zsh, THIS MUST BE INSTALLED LAST!
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    # Install custom dotfiles
    echo '# Create dotfiles directory variable' > $HOME/.zshrc
    echo 'export DOTFILES_PATH="$HOME/bin/dotfiles"' >> $HOME/.zshrc
    echo '# Source zshrc' >> $HOME/.zshrc
    echo 'source $DOTFILES_PATH/bash/zshrc' >> $HOME/.zshrc

  fi
}

function install_rvm_arch_only {
  if [[ "$isArch" =~ ^/ ]]; then
    read -p "You must visit rvm.io and install GPG keys before first use or it will not work!" choice
    curl -L get.rvm.io > rvm-install && bash < ./rvm-install
    rm rvm-install
  fi
}

function install_docker {
  if [[ "$isDebian" =~ ^/ ]]; then
    sudo apt -y install docker.io
    sudo systemctl start docker
    sudo systemctl enable docker
    sudo groupadd docker
    sudo gpasswd -a $USER docker
  elif [[ "$isArch" =~ ^/ ]]; then
    sudo pacman -S docker
    sudo systemctl start docker
    sudo systemctl enable docker
    sudo groupadd docker
    sudo gpasswd -a $USER docker
  fi
}

function install_docker_compose {
  if [[ "$isDebian" =~ ^/ ]]; then
    sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
  elif [[ "$isArch" =~ ^/ ]]; then
    sudo pacman -S docker-compose
  fi
}

function install_termite_arch_only {
  if [[ "$isArch" =~ ^/ ]]; then
    sudo pacman -S termite
    mkdir -p $HOME/.config/termite
    ln -s $HOME/bin/dotfiles/termite/config $HOME/.config/termite/config
  fi
}

function install_heroku_debian_only {
  if [[ "$isDebian" =~ ^/ ]]; then
    sudo snap install heroku --classic
    ln -s /snap/bin/heroku /usr/bin/heroku
  fi
}

function install_xorg_arch_only {
  if [[ "$isArch" =~ ^/ ]]; then
    sudo pacman -S xorg-server xorg-xinit
    echo "exec i3" > ~/.xinitrc
  fi
}

function install_atigfx_arch_only {
  if [[ "$isArch" =~ ^/ ]]; then
    sudo pacman -S mesa xf86-video-ati mesa-vdpau \
      libva-mesa-driver libva-vdpau-driver
    read -p "Add 'radeon' to MODULES in next file"
    sudo vim /etc/mkinitcpio.conf
    sudo mkinitcpio -p linux
    sudo ln -s $HOME/bin/dotfiles/i3/20-radeon.conf /etc/X11/xorg.conf.d/.
    sudo rm /etc/environment
    sudo ln -s $HOME/bin/dotfiles/i3/environment /etc/environment
  fi
}

function install_i3_gaps_arch_only {
  if [[ "$isArch" =~ ^/ ]]; then
    sudo pacman -S i3-gaps i3status dmenu feh compton volumeicon xorg-xrandr xf86-input-synaptics
    #touchpad drivers
    sudo ln -s $HOME/bin/dotfiles/i3/70-synaptics.conf /etc/X11/xorg.conf.d/.
    mkdir -p $HOME/.config/i3
    ln -s $HOME/bin/dotfiles/i3/config $HOME/.config/i3/config
    mkdir -p $HOME/Pictures
    cp $HOME/bin/dotfiles/i3/desktop.jpg $HOME/Pictures/.
  fi
}

function install_vbox_arch_only {
  read -p "VirtualBox tools: This only installs the linux-headers.. You still must insert the vbutils cd and install 'sudo sh ./VboxLinuxAdditions.run'" choice
  if [[ "$isArch" =~ ^/ ]]; then
    sudo pacman -S \
      linux-headers \

  fi
}

################################


# Here is where the magic happens
echo "You must have passwords set for both root and the account"
echo "that you are logged into right now.  You also must continuously"
echo "exit out of each prompt until you see 'Finished install!'."
echo "Happy installing!"
Install
echo "Finished install!"

# Done




