#!/bin/bash

# Add in any pacman packages to install here
PACMAN_PACKAGES=(
  cmake
  curl
  htop
  the_silver_searcher
  tree
  chromium
  python
  python-pip
  python2
  python2-pip
  #docker-compose
)

# Add in any custom packages to install here
CUSTOM_PACKAGES=(
  add_git
  add_openssh
  #add_docker
  add_fzf
  add_termite
  add_xorg
  add_i3_gaps
  add_vbox_utils
  add_neovim_tmux
  add_grub
  #add_atigfx
  #add_set_bright     # NEEDS add_atigfx
  #add_synaptics_touchpad
  add_zsh_oh_my_zsh  # MUST BE LAST!
)

#################################################################
#################################################################
# Custom Packages
#################################################################
#################################################################

# Variables
DOTFILES_PATH="$HOME/bin/dotfiles"
MYNVIMPATH="$DOTFILES_PATH/nvim"
MYBASHPATH="$DOTFILES_PATH/bash"
MYTMUXPATH="$DOTFILES_PATH/tmux"
MYGITPATH="$DOTFILES_PATH/git"
INSTALL_PACKAGES=()
PAC="sudo pacman -S"
PAC_FLAGS="--needed --noconfirm"
PAC_UPDATE="sudo pacman -Syu"
PACMAN="$PAC $PAC_FLAGS"

#################################################################
# Packages
#################################################################

# git
#################################################################
function add_git {
  PACMAN_PACKAGES+=(git)
  INSTALL_PACKAGES+=(install_git)
}
function install_git {
  # Git custom dotfiles
  rm -f $HOME/.gitconfig
  ln -sfn $MYGITPATH/gitconfig $HOME/.gitconfig
}
#################################################################

# openssh
#################################################################
function add_openssh {
  PACMAN_PACKAGES+=(openssh)
  INSTALL_PACKAGES+=(install_openssh)
}
function install_openssh {
  sudo systemctl restart sshd
}
#################################################################

# docker
#################################################################
function add_docker {
  PACMAN_PACKAGES+=(docker)
  INSTALL_PACKAGES+=(install_docker)
}
function install_docker {
  sudo systemctl start docker
  sudo systemctl enable docker
  sudo groupadd docker
  sudo gpasswd -a $USER docker
}
#################################################################

# fzf
#################################################################
function add_fzf {
  #PACMAN_PACKAGES+=()
  INSTALL_PACKAGES+=(install_fzf)
}
function install_fzf {
  git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
  $HOME/.fzf/install
}
#################################################################

# termite
#################################################################
function add_termite {
  PACMAN_PACKAGES+=(termite)
  INSTALL_PACKAGES+=(install_termite)
}
function install_termite {
  mkdir -p $HOME/.config/termite
  ln -sfn $DOTFILES_PATH/termite/config $HOME/.config/termite/config
  sudo mkdir -p /usr/share/fonts/nerd-fonts
  sudo curl -L 'https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/RobotoMono/Regular/complete/Roboto%20Mono%20Nerd%20Font%20Complete.ttf?raw=true' -o "/usr/share/fonts/nerd-fonts/roboto_mono_nerd_font_complete_mono.ttf"
  sudo fc-cache
}
#################################################################

# xorg
#################################################################
function add_xorg {
  PACMAN_PACKAGES+=(xorg-server xorg-xinit)
  INSTALL_PACKAGES+=(install_xorg)
}
function install_xorg {
  echo "exec i3" > ~/.xinitrc
  echo    "Install Xorg: Make sure to add startup script to the end of your zshrc"
  read -p "              (Press ENTER to continue)" en
}
#################################################################

# i3-gaps
#################################################################
function add_i3_gaps {
  PACMAN_PACKAGES+=(i3-gaps i3status dmenu feh compton volumeicon xorg-xrandr)
  INSTALL_PACKAGES+=(install_i3_gaps)
}
function install_i3_gaps {
  mkdir -p $HOME/.config/i3
  ln -sfn $DOTFILES_PATH/i3/config $HOME/.config/i3/config
  mkdir -p $HOME/Pictures
  cp $DOTFILES_PATH/i3/desktop.jpg $HOME/Pictures/.
}
#################################################################

# vbox-utils
#################################################################
function add_vbox_utils {
  PACMAN_PACKAGES+=(linux-headers)
  INSTALL_PACKAGES+=(install_vbox_utils)
}
function install_vbox_utils {
  echo    "VirtualBox tools: This only installs the necessary linux-headers.."
  echo    "                  You still must install the guest utils from the CD."
  echo    "                  Don't forget to add 'vboxsf' group to current user."
  read -p "                  (Press ENTER to continue)" en
}
#################################################################

# neovim tmux
#################################################################
function add_neovim_tmux {
  PACMAN_PACKAGES+=(neovim tmux python python-pip)
  INSTALL_PACKAGES+=(install_neovim_tmux)
}
function install_neovim_tmux {
  sudo pip install neovim
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  echo    "Tmux: In tmux, you must run <prefix><Shift-i> to load plugins"
  read -p "      (Press ENTER to continue)" en
  echo    "Neovim: In Neovim, you must run :PlugInstall"
  read -p "        (Press ENTER to continue)" en

  # Neovim custom dotfiles
  mkdir -p ~/.local/share/nvim/site/autoload/
  mkdir -p ~/.config/nvim/
  echo ':source $MYNVIMPATH/init.vim' > $HOME/.config/nvim/init.vim
  git clone https://github.com/junegunn/vim-plug.git $HOME/.local/share/nvim/site/autoload/vim-plug
  cp $HOME/.local/share/nvim/site/autoload/vim-plug/plug.vim $HOME/.local/share/nvim/site/autoload/.
  rm -Rf $HOME/.local/share/nvim/site/autoload/vim-plug

  # Tmux custom dotfiles
  ln -sfn $MYTMUXPATH/tmux.conf $HOME/.tmux.conf
}
#################################################################

# grub
#################################################################
function add_grub {
  #PACMAN_PACKAGES+=()
  INSTALL_PACKAGES+=(install_grub)
}
function install_grub {
  sudo rm -Rf /etc/default/grub
  sudo ln -s $DOTFILES_PATH/grub/grub /etc/default/grub
  sudo grub-mkconfig -o /boot/grub/grub.cfg
}
#################################################################

# atigfx
#################################################################
function add_atigfx {
  PACMAN_PACKAGES+=(mesa xf86-video-ati mesa-vdpau libva-mesa-driver libva-vdpau-driver)
  INSTALL_PACKAGES+=(install_atigfx)
}
function install_atigfx {
  echo    "ATIGFX: Add 'radeon' to MODULES in next file"
  read -p "        (Press ENTER to continue)" en
  sudo vim /etc/mkinitcpio.conf
  sudo mkinitcpio -p linux
  sudo ln -sfn $DOTFILES_PATH/i3/20-radeon.conf /etc/X11/xorg.conf.d/.
  sudo rm /etc/environment
  sudo ln -sfn $DOTFILES_PATH/i3/environment /etc/environment
}
#################################################################

# set_bright
#################################################################
function add_set_bright {
  PACMAN_PACKAGES+=()
  INSTALL_PACKAGES+=(install_set_bright)
}
function install_set_bright {
  sudo ln -sfn $DOTFILES_PATH/i3/backlight.rules /etc/udev/rules.d/.
  sudo usermod -aG video $USER
}
#################################################################

# synaptics_touchpad
#################################################################
function add_synaptics_touchpad {
  PACMAN_PACKAGES+=(xf86-input-synaptics)
  INSTALL_PACKAGES+=(install_synaptics_touchpad)
}
function install_synaptics_touchpad {
  sudo ln -sfn $DOTFILES_PATH/i3/70-synaptics.conf /etc/X11/xorg.conf.d/.
}
#################################################################

# zsh oh_my_zsh
#################################################################
function add_zsh_oh_my_zsh {
  PACMAN_PACKAGES+=(zsh zsh-completions)
  INSTALL_PACKAGES+=(install_zsh_oh_my_zsh)
}
function install_zsh_oh_my_zsh {
  if [[ ! "$(which zsh)" =~ ^/ ]]; then
    chsh -s $(which zsh)

    echo    "----> You must type exit at the next prompt to finish install!"
    read -p "      (Press ENTER to continue)" en
 
    # Install oh-my-zsh, THIS MUST BE INSTALLED LAST!
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    # Install custom dotfiles
    echo '# Create dotfiles directory variable' > $HOME/.zshrc
    echo "export DOTFILES_PATH=\"${DOTFILES_PATH}\"" >> $HOME/.zshrc
    echo '# Source zshrc' >> $HOME/.zshrc
    echo 'source $DOTFILES_PATH/bash/zshrc' >> $HOME/.zshrc
  fi
}
#################################################################

#################################################################
#################################################################
# Core - Below shouldn't need to be touched!
#################################################################
#################################################################
echo    "--> You must have passwords set for both root and the account"
echo    "    that you are logged into right now.  You also must continuously"
echo    "    exit out of each prompt until you see 'Finished install!'."
echo    "    Happy installing!"
read -p "    (Press ENTER to continue)" en

set -e  # exit if something fails

# Load Custom Packages
for package in ${CUSTOM_PACKAGES[@]}; do
  $package
done

# Install Pacman Packages
$PAC_UPDATE
$PACMAN $(printf " %s" "${PACMAN_PACKAGES[@]}")

# Install Custom Packages
for package in ${INSTALL_PACKAGES[@]}; do
  $package
done

echo    "----> Finished!"



