#!/bin/bash

################################################################################
## ALACRITTY INSTALL ###########################################################
################################################################################

# Get the directory of the currently executing script
SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# Source helpers
source "$SCRIPT_DIR/helpers"

# Install Alacritty
_common_install() {
  cprint -p "Running common install"

  # run the common commands here
  cprint "Old Files: backing up or removing symlinks.."
  backup_or_remove "$HOME/.config/alacritty"

  cprint "Creating new directories.."
  ln -s "$HOME/bin/dotfiles/alacritty/alacritty" "$HOME/.config/alacritty"
}

_arch_install() {
  cprint -p "Installing Alacritty for Arch!"

  cprint "Gathering dependencies.."
  sudo pacman -Syu --needed alacritty

  _common_install

  cprint "Finished installing Alacritty for Arch!"
}

_ubuntu_install() {
  cprint -p "Ubuntu Install: Under Construction.."
}

_macos_install() {
  cprint -p "MacOS Install: Under Construction.."
}

main() {
  # Figure out what OS we're running
  case $OS_TYPE in
    $OS_ARCH_LINUX)
      _arch_install
      ;;
    $OS_UBUNTU)
      _ubuntu_install
      ;;
    $OS_MACOS)
      _macos_install
      ;;
    $OS_OTHER_LINUX)
      cprint "Running an unknown Linux distribution.."
      cprint "This OS is not supported.. Exiting."
      exit 1
      ;;
    $OS_UNKNOWN)
      cprint "Running an unknown OS.."
      cprint "This OS is not supported.. Exiting."
      exit 1
      ;;
  esac
}
main
