#!/bin/bash

################################################################################
## SUCKLESS INSTALL ############################################################
################################################################################

# Get the directory of the currently executing script
SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# Source helpers
source "$SCRIPT_DIR/helpers"

# Install DWM
_common_install() {
  cprint -p "Running common install"

  # run the common commands here
  cprint "Old Files: backing up or removing symlinks.."
  backup_or_remove "$HOME/.config/suckless/dwm"
  backup_or_remove "$HOME/.config/suckless/dmenu"

  cprint "Creating new directories.."
  mkdir -p "$HOME/.config/suckless"
  git clone https://git.suckless.org/dwm "$HOME/.config/suckless/dwm"
  git clone https://git.suckless.org/dmenu "$HOME/.config/suckless/dmenu"

  cprint "Making and installing.."
  cd "$HOME/.config/suckless/dwm"; sudo make clean install
  cd "$HOME/.config/suckless/dmenu"; sudo make clean install

  cprint "Adding startup codes to user account.."
  echo "exec dwm" >> "$HOME/.xinitrc"
  echo "startx" >> "$HOME/.bash_profile"
  echo "startx" >> "$HOME/.zsh_profile"

  cprint "Remember to modify config.h for dwm to add your terminal to terminal source.."
}

_arch_install() {
  cprint -p "Installing DWM for Arch!"

  cprint "Gathering dependencies.."
  sudo pacman -Syu --needed git base-devel xorg-server xorg-xinit libx11 libxinerama libxft webkit2gtk

  _common_install

  cprint "Finished installing DWM for Arch!"
}

_ubuntu_install() {
  cprint -p "Ubuntu Install: Under Construction.."
}

_macos_install() {
  cprint -p "MacOS Install: Under Construction.."
}

main() {
  # Figure out what OS we're running
  case $OS_TYPE in
    $OS_ARCH_LINUX)
      _arch_install
      ;;
    $OS_UBUNTU)
      _ubuntu_install
      ;;
    $OS_MACOS)
      _macos_install
      ;;
    $OS_OTHER_LINUX)
      cprint "Running an unknown Linux distribution.."
      cprint "This OS is not supported.. Exiting."
      exit 1
      ;;
    $OS_UNKNOWN)
      cprint "Running an unknown OS.."
      cprint "This OS is not supported.. Exiting."
      exit 1
      ;;
  esac
}
main
