#!/bin/bash

################################################################################
## QEMU INSTALL ################################################################
################################################################################

# Get the directory of the currently executing script
SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# Source helpers
source "$SCRIPT_DIR/helpers"

_arch_install() {
  cprint -p "Installing Qemu for Arch!"

  cprint "Gathering dependencies.."
  sudo pacman -Syu --needed qemu virt-manager virt-viewer dnsmasq vde2\
    bridge-utils openbsd-netcat ebtables iptables libguestfs nvidia swtpm

  sudo systemctl enable libvirtd.service
  sudo systemctl start libvirtd.service
  systemctl status libvirtd.service

  sudo usermod -a -G libvirt $(whoami)
  sudo systemctl restart libvirtd.service

  cprint "Finished installing Qemu for Arch!"
}

_ubuntu_install() {
  cprint -p "Ubuntu Install: Under Construction.."
}

_macos_install() {
  cprint -p "MacOS Install: Under Construction.."
}

main() {
  # Figure out what OS we're running
  case $OS_TYPE in
    $OS_ARCH_LINUX)
      _arch_install
      ;;
    $OS_UBUNTU)
      _ubuntu_install
      ;;
    $OS_MACOS)
      _macos_install
      ;;
    $OS_OTHER_LINUX)
      cprint "Running an unknown Linux distribution.."
      cprint "This OS is not supported.. Exiting."
      exit 1
      ;;
    $OS_UNKNOWN)
      cprint "Running an unknown OS.."
      cprint "This OS is not supported.. Exiting."
      exit 1
      ;;
  esac
}
main
