#!/bin/bash

################################################################################
## YAY INSTALL #################################################################
################################################################################

# Get the directory of the currently executing script
SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# Source helpers
source "$SCRIPT_DIR/helpers"

# Install YAY
_common_install() {
  cprint -p "Running common install"

  # run the common commands here
  cprint "Old Files: backing up or removing symlinks.."
  backup_or_remove "/tmp/yayinstall"

  cprint "Creating new directories.."
  mkdir -p "/tmp/yayinstall"

  cd "/tmp/yayinstall"
  git clone https://aur.archlinux.org/yay.git

  cd yay
  cprint "Making and installing.."

  makepkg -si
}

_arch_install() {
  cprint -p "Installing YAY for Arch!"

  _common_install

  cprint "Gathering dependencies.."
  sudo pacman -Syu --needed git base-devel

  cprint "Finished installing YAY for Arch!"
}

_ubuntu_install() {
  cprint -p "Ubuntu Install: Under Construction.."
}

_macos_install() {
  cprint -p "MacOS Install: Under Construction.."
}

main() {
  # Figure out what OS we're running
  case $OS_TYPE in
    $OS_ARCH_LINUX)
      _arch_install
      ;;
    $OS_UBUNTU)
      _ubuntu_install
      ;;
    $OS_MACOS)
      _macos_install
      ;;
    $OS_OTHER_LINUX)
      cprint "Running an unknown Linux distribution.."
      cprint "This OS is not supported.. Exiting."
      exit 1
      ;;
    $OS_UNKNOWN)
      cprint "Running an unknown OS.."
      cprint "This OS is not supported.. Exiting."
      exit 1
      ;;
  esac
}
main
